# Generated by Django 5.1.6 on 2025-02-16 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_message_id_feedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="model_response",
        ),
    ]
